language: php

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

php:
    - 5.4
    - 5.5

services:
    - mongodb

before_script:
    - phpenv config-add .travis.php.ini
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
