language: php

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

php:
    # Although the bundle's implementation code works with PHP 5.4, the tests use `::class`
    # which is only available since 5.5. 5.4 has reached it's end of life, so we won't bother
    # with actively testing the implementation code against it.
    - 5.5
    - 5.6

services:
    - mongodb

before_script:
    - phpenv config-add .travis.php.ini
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
